# Generated by Django 5.2.8 on 2026-04-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbienesInmuebles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TBNoMatricula', models.CharField(max_length=50)),
                ('TBDireccion', models.CharField(max_length=150)),
                ('TCId', models.CharField(max_length=10)),
                ('TBTipo', models.CharField(max_length=20)),
                ('TBObs', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tbienesinmuebles',
                'constraints': [models.UniqueConstraint(fields=('TBNoMatricula', 'TBDireccion'), name='uq_tbienes_matricula_direccion')],
            },
        ),
    ]
