# Generated by Django 5.2.8 on 2026-04-12 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
        ('tablas_maestras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='THistorial',
            fields=[
                ('TRHId', models.AutoField(primary_key=True, serialize=False)),
                ('TRHValorAdeudado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('TRHValorPagado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('TRHSaldo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('TRHEstado', models.CharField(default='ABIERTO', max_length=50)),
                ('TRHFechaPago', models.DateField(blank=True, null=True)),
                ('TRHObservacion', models.TextField(blank=True, null=True)),
                ('TRHFechaReporte', models.DateTimeField(auto_now_add=True)),
                ('TUUserName', models.CharField(blank=True, max_length=150, null=True)),
                ('TCAIDContrato', models.ForeignKey(db_column='TCAIDContrato', on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='contrato.contratoarriendo')),
                ('TRHTipoReporte', models.ForeignKey(db_column='TRHTipoReporte', on_delete=django.db.models.deletion.PROTECT, related_name='historial_reportes', to='tablas_maestras.ttiporeporte')),
            ],
            options={
                'db_table': 'thistorial',
                'unique_together': {('TCAIDContrato', 'TRHTipoReporte')},
            },
        ),
    ]
