# Generated by Django 5.2.8 on 2026-05-11 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
        ('tablas_maestras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAlertas',
            fields=[
                ('TAId', models.AutoField(primary_key=True, serialize=False)),
                ('TUUserName', models.CharField(max_length=150)),
                ('TAValorAdeudado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('TAValorPagado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('TASaldo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('TAEstado', models.CharField(blank=True, default='ABIERTO', max_length=50, null=True)),
                ('TAFechaPago', models.DateField(blank=True, null=True)),
                ('TAObservacion', models.TextField(blank=True, null=True)),
                ('TAFechaReporte', models.DateTimeField(auto_now_add=True)),
                ('TATipoReporte', models.ForeignKey(blank=True, db_column='TATipoReporte', null=True, on_delete=django.db.models.deletion.PROTECT, to='tablas_maestras.ttiporeporte')),
                ('TCAIDContrato', models.ForeignKey(blank=True, db_column='TCAIDContrato', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='contrato.contratoarriendo')),
            ],
            options={
                'db_table': 'talertas',
            },
        ),
        migrations.CreateModel(
            name='THistorial',
            fields=[
                ('TRHId', models.AutoField(primary_key=True, serialize=False)),
                ('TRHValorAdeudado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('TRHEstado', models.CharField(default='ABIERTO', max_length=50)),
                ('TRHObservacion', models.TextField(blank=True, null=True)),
                ('TRHFechaReporte', models.DateTimeField(auto_now_add=True)),
                ('TUUserName', models.CharField(blank=True, max_length=150, null=True)),
                ('TCAIDContrato', models.ForeignKey(db_column='TCAIDContrato', on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='contrato.contratoarriendo')),
                ('TRHTipoReporte', models.ForeignKey(db_column='TRHTipoReporte', on_delete=django.db.models.deletion.PROTECT, related_name='historial_reportes', to='tablas_maestras.ttiporeporte')),
            ],
            options={
                'db_table': 'thistorial',
                'unique_together': {('TCAIDContrato', 'TRHTipoReporte')},
            },
        ),
        migrations.CreateModel(
            name='ThistorialPagos',
            fields=[
                ('THPId', models.AutoField(primary_key=True, serialize=False)),
                ('TRHFechaPago', models.DateField()),
                ('TRHValorPagado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('TRHPobservacion', models.TextField(blank=True, null=True)),
                ('TUUserName', models.CharField(max_length=150)),
                ('TCAIDContrato', models.ForeignKey(db_column='TCAIDContrato', on_delete=django.db.models.deletion.CASCADE, to='contrato.contratoarriendo')),
                ('TRHId', models.ForeignKey(db_column='TRHId', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='referencias.thistorial')),
            ],
            options={
                'db_table': 'thistorialpagos',
            },
        ),
    ]
