# Generated by Django 5.2.8 on 2026-04-26 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0001_initial'),
        ('referencias', '0001_initial'),
        ('tablas_maestras', '0003_add_tciudades_tccodigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAlertas',
            fields=[
                ('TAId', models.AutoField(primary_key=True, serialize=False)),
                ('TUUserName', models.CharField(max_length=150)),
                ('TAValorAdeudado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('TAValorPagado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('TASaldo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('TAEstado', models.CharField(blank=True, default='ABIERTO', max_length=50, null=True)),
                ('TAFechaPago', models.DateField(blank=True, null=True)),
                ('TAObservacion', models.TextField(blank=True, null=True)),
                ('TAFechaReporte', models.DateTimeField(auto_now_add=True)),
                ('TATipoReporte', models.ForeignKey(blank=True, db_column='TATipoReporte', null=True, on_delete=django.db.models.deletion.PROTECT, to='tablas_maestras.ttiporeporte')),
                ('TCAIDContrato', models.ForeignKey(blank=True, db_column='TCAIDContrato', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='contrato.contratoarriendo')),
            ],
            options={
                'db_table': 'talertas',
            },
        ),
    ]
