# Generated by Django 5.2.8 on 2026-04-26 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0001_initial'),
        ('referencias', '0002_talertas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thistorial',
            name='TRHFechaPago',
        ),
        migrations.RemoveField(
            model_name='thistorial',
            name='TRHSaldo',
        ),
        migrations.RemoveField(
            model_name='thistorial',
            name='TRHValorPagado',
        ),
        migrations.CreateModel(
            name='ThistorialPagos',
            fields=[
                ('THPId', models.AutoField(primary_key=True, serialize=False)),
                ('TRHFechaPago', models.DateField()),
                ('TRHValorPagado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('TRHPobservacion', models.TextField(blank=True, null=True)),
                ('TUUserName', models.CharField(max_length=150)),
                ('TCAIDContrato', models.ForeignKey(db_column='TCAIDContrato', on_delete=django.db.models.deletion.CASCADE, to='contrato.contratoarriendo')),
                ('TRHId', models.ForeignKey(db_column='TRHId', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='referencias.thistorial')),
            ],
            options={
                'db_table': 'thistorialpagos',
            },
        ),
    ]
