
services:
  db:
    image: postgres:15-alpine
    container_name: referenciate_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-12345}
      POSTGRES_DB: ${DB_NAME:-referencedb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: referenciate_backend
    restart: always
    volumes:
      - static_volume:/app/backend/staticfiles 
    working_dir: /app
    environment:
      - DEBUG=${DEBUG:-False}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-www.referenciate.com,referenciate.com,localhost,127.0.0.1,2.24.76.180}
      - DB_NAME=${DB_NAME:-referencedb}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-12345}
      - DB_HOST=db
      - DB_PORT=5432
      - PORT=8000
      - DJANGO_SETTINGS_MODULE=backend.settings
      - PYTHONPATH=/app/backend
    depends_on:
      - db
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --chdir backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: referenciate_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "0.0.0.0:80:80"
      - "443:443"
    volumes:
      # CRUCIAL: Compartimos la carpeta de estáticos con Nginx
      - static_volume:/usr/share/nginx/html/static/backend
      # CRUCIAL: Aseguramos que Nginx use tu archivo de configuración corregido
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro # <--- ESTO PASA EL SSL AL CONTENEDOR
volumes:
  postgres_data:
  static_volume: # Definimos el volumen global para que ambos contenedores lo vean
