# Generated by Django 5.2.8 on 2026-05-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TCiudades',
            fields=[
                ('TCId', models.AutoField(primary_key=True, serialize=False)),
                ('TCNombre', models.CharField(blank=True, help_text='Nombre de la ciudad', max_length=100, null=True)),
                ('TCDepartamento', models.CharField(blank=True, help_text='Departamento/Provincia', max_length=100, null=True)),
                ('TCPais', models.CharField(blank=True, help_text='País', max_length=100, null=True)),
                ('TCFechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('TCFechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'tciudades',
                'ordering': ['TCId'],
            },
        ),
        migrations.CreateModel(
            name='TEmpresas',
            fields=[
                ('TEId', models.AutoField(primary_key=True, serialize=False)),
                ('TENit', models.CharField(blank=True, help_text='NIT de la empresa', max_length=20, null=True)),
                ('TENombre', models.CharField(blank=True, help_text='Nombre de la empresa', max_length=200, null=True)),
                ('TEDireccion', models.CharField(blank=True, help_text='Dirección de la empresa', max_length=300, null=True)),
                ('TECelular', models.CharField(blank=True, help_text='Celular de contacto', max_length=20, null=True)),
                ('TETelefono', models.CharField(blank=True, help_text='Teléfono fijo', max_length=20, null=True)),
                ('TEEmail', models.EmailField(blank=True, help_text='Email de la empresa', max_length=254, null=True)),
                ('TEContacto', models.CharField(blank=True, help_text='Nombre del contacto', max_length=100, null=True)),
                ('TEDescripcion', models.CharField(help_text='Descripción de la empresa', max_length=200)),
                ('TEActivo', models.BooleanField(default=True, help_text='Indica si la empresa está activa')),
                ('TEFechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('TEFechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'tempresas',
                'ordering': ['TEId'],
            },
        ),
        migrations.CreateModel(
            name='TPuntajeColor',
            fields=[
                ('TPCNivel', models.CharField(help_text='Nivel de puntaje', max_length=50, primary_key=True, serialize=False)),
                ('TPCValorInicial', models.IntegerField(help_text='Valor inicial del rango de puntaje')),
                ('TPCValorFinal', models.IntegerField(help_text='Valor final del rango de puntaje')),
                ('TPCColor', models.CharField(help_text='Código de color (ej: #FF0000) o nombre del color', max_length=50)),
                ('TPCEvaluacion', models.CharField(blank=True, help_text='Evaluación asociada al nivel de puntaje', max_length=200, null=True)),
                ('TPCComentario', models.TextField(blank=True, help_text='Comentario o descripción detallada del nivel', null=True)),
                ('TPCActivo', models.BooleanField(default=True, help_text='Indica si la configuración está activa')),
                ('TPCFechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('TPCFechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Color de Puntaje',
                'verbose_name_plural': 'Configuraciones de Color de Puntaje',
                'db_table': 'tpuntajecolor',
                'ordering': ['TPCValorInicial'],
            },
        ),
        migrations.CreateModel(
            name='TTipoReporte',
            fields=[
                ('TRHTipoReporte', models.CharField(help_text='Código del tipo de reporte', max_length=100, primary_key=True, serialize=False)),
                ('TRDescripcion', models.TextField(blank=True, help_text='Descripción del tipo de reporte', null=True)),
                ('TRPeso', models.IntegerField(blank=True, help_text='Peso o prioridad del reporte', null=True)),
                ('TRActivo', models.BooleanField(default=True, help_text='Indica si el tipo de reporte está activo')),
                ('TRFechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('TRFechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Reporte',
                'verbose_name_plural': 'Tipos de Reporte',
                'db_table': 'ttiporeporte',
                'ordering': ['TRHTipoReporte'],
            },
        ),
    ]
