# Generated by Django 5.2.8 on 2026-04-12 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablas_maestras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('TPTipoDocumento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NT', 'NIT'), ('PA', 'Pasaporte'), ('PR', 'Permiso Temporal de Residencia')], max_length=10)),
                ('TPNoDocumento', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('TPNombres', models.CharField(max_length=100)),
                ('TPApellidos', models.CharField(max_length=100)),
                ('TPDireccionResidencia', models.CharField(max_length=200)),
                ('TPCelular1', models.CharField(max_length=20)),
                ('TPCelular2', models.CharField(blank=True, max_length=20, null=True)),
                ('TPBarriosZona', models.CharField(blank=True, max_length=100, null=True)),
                ('TPPuntaje', models.IntegerField(default=1000)),
                ('TCId', models.ForeignKey(db_column='TCId', on_delete=django.db.models.deletion.PROTECT, to='tablas_maestras.tciudades')),
                ('TEId', models.ForeignKey(db_column='TEId', on_delete=django.db.models.deletion.PROTECT, to='tablas_maestras.tempresas')),
            ],
            options={
                'db_table': 'tpersonas',
                'managed': True,
            },
        ),
    ]
