# Generated by Django 5.2.8 on 2026-05-11 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbienesInmuebles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TBNoMatricula', models.CharField(max_length=50)),
                ('TBDireccion', models.CharField(max_length=150)),
                ('TCId', models.CharField(max_length=10)),
                ('TBTipo', models.CharField(max_length=20)),
                ('TBObs', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=150)),
                ('numero_contrato_energia', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_contrato_agua', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_contrato_gas', models.CharField(blank=True, max_length=50, null=True)),
                ('certificado_tradicion', models.FileField(blank=True, null=True, upload_to='certificados/')),
            ],
            options={
                'db_table': 'tbienesinmuebles',
                'constraints': [models.UniqueConstraint(fields=('TBNoMatricula', 'TBDireccion'), name='uq_tbienes_matricula_direccion')],
            },
        ),
        migrations.CreateModel(
            name='FotoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='inmuebles/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='bienesinmuebles.tbienesinmuebles')),
            ],
            options={
                'db_table': 'tfotosinmueble',
            },
        ),
    ]
