# Generated by Django 5.2.8 on 2026-04-21 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienesinmuebles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='inmuebles/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='bienesinmuebles.tbienesinmuebles')),
            ],
            options={
                'db_table': 'tfotosinmueble',
            },
        ),
    ]
