# Generated by Django 5.2.8 on 2026-04-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienesinmuebles', '0002_fotoinmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbienesinmuebles',
            name='certificado_tradicion',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AddField(
            model_name='tbienesinmuebles',
            name='numero_contrato_agua',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbienesinmuebles',
            name='numero_contrato_energia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbienesinmuebles',
            name='numero_contrato_gas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
