# Generated by Django 5.2.8 on 2026-04-12 13:49

import contrato.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoArriendo',
            fields=[
                ('TCAIDContrato', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('TBNoMatricula', models.CharField(max_length=50)),
                ('TBDireccion', models.CharField(max_length=150)),
                ('TCAFechaContrato', models.DateField()),
                ('TCAFechaInicioContrato', models.DateField()),
                ('TCAFechaEntregaInmueble', models.DateField(blank=True, null=True)),
                ('TCADuracionContrato', models.IntegerField()),
                ('TCATipoDuracion', models.CharField(choices=[('DD', 'Días'), ('MM', 'Meses'), ('AA', 'Años')], max_length=2)),
                ('TCAValorCanonContrato', models.DecimalField(decimal_places=2, max_digits=14)),
                ('TCAFechaReporteContrato', models.DateField(auto_now_add=True)),
                ('TCAArchivoPDF', models.FileField(blank=True, max_length=255, null=True, upload_to=contrato.models.contrato_pdf_upload_to)),
            ],
            options={
                'db_table': 'tcontratoarriendo',
            },
        ),
        migrations.CreateModel(
            name='ContratoArriendoRelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TPNoDocumento', models.CharField(max_length=50)),
                ('TCARTipoParticipacion', models.CharField(choices=[('ARRENDADOR', 'Arrendador'), ('ARRENDATARIO', 'Arrendatario'), ('CODEUDOR', 'Codeudor')], max_length=20)),
                ('TCAIDContrato', models.ForeignKey(db_column='TCAIDContrato', on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='contrato.contratoarriendo')),
            ],
            options={
                'db_table': 'tcontratoarriendorelacion',
                'unique_together': {('TCAIDContrato', 'TPNoDocumento')},
            },
        ),
    ]
