# Generated by Django 5.2.8 on 2026-04-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
